name: Static Analysis

on: [push, pull_request]

jobs:
  static_analysis:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.10"
        include:
          - os: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python dependencies
      run: |
        python3 -m pip install -U pip
        python3 -m pip install .[dev]
    - name: Run static analysis checks
      run: make static-analysis
